[package]
name = "sudoku"
version = "0.1.0"
authors = ["G. Ralph Kuntz, MD <grk@usa.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
chrono = "0.4"

[dependencies]
clap = "2.33.0"